// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npngxiprlrsodvggbaqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbmd4aXBybHJzb2R2Z2diYXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NTAyODMsImV4cCI6MjA4NTMyNjI4M30.E8f2QiwA84EI155cD2r15FG48pz0zf7MCDjx91eoJYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});